server:
  port: 8080

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.17.0.1:3306/weblog?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: han414885140
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: Weblog-HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

#=================================================================
# JWT 配置 (新增部分，解决启动报错)
#=================================================================
jwt:
  # 签发人
  issuer: suoyike
  # 秘钥
  secret: wu3bCrL/g6OKGPO0zm24xkuhqvc0OUCPV9P4jO7VPmsvOL9S1bJUIy03ahTWGxhylLx6THtp/d0t3BmukVob/g==
  # token 过期时间（单位：分钟） 24*60
  tokenExpireTime: 1440
  # token 请求头中的 key 值
  tokenHeaderKey: Authorization
  # token 请求头中的 value 值前缀
  tokenPrefix: Bearer

#=================================================================
# MinIO 配置
#=================================================================
minio:
  endpoint: https://img.suoyikehan.com
  accessKey: suoyike
  secretKey: han414885140
  bucketName: weblog

#=================================================================
# Lucene 全文检索
#=================================================================
lucene:
  indexDir: /app/weblog/lucene-index # lucene 索引存放的位置
